spring:
  application:
    name: cinema-tcs
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties.mail.smtp:
          auth: true
          starttls.enable: true
    default-encoding: UTF-8

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

jwt:
  secret: ${JWT_SECRET}